curl/trurl

- urler.c
The help output misses some line breaks .
Before :
```
$ ./urler -h
Usage: [options] [URL]
-h,--help             - this help
INPUT
--fragment [fragment] - set this fragment
--host [host]         - set this host name
--options [options]   - set these options
--password [secret]   - set this password
--path [path]         - set this path
--port [port]         - set this port number
--query [query]       - set this query
--redirect [URL]      - redirect the base URL to this
--scheme [scheme]     - set this scheme
--url [base URL]      - URL to start with
--user [name]         - set this user
--zoneid [zoneid]     - set this zone id
OUTPUT
--only-fragment       - output only the fragment part  --only-host           - output only the host part  --only-options        - output only the options …
```
> Add line-breaks in help() output

- urler.c
Extract `PROGNAME` variable to hold the program name.
It fixes a typo in the current code, and it will help change the name if decided (re. #1).
> Use variable for program name

- Makefile
Currently, installation will fail if `$(MANDIR)/man1/` does not exist. Fix that by creating the directory first.
Also, since the manpage is a `install` target, make sure it follows `DESTDIR`.
> Makefile: create man1 directory if missing; install manpage to DESTDIR

- Makefile
Update the Makefile to add support for a prefix in order support tools like Homebrew.
> Makefile: add prefix variable to support tools like homebrew

- Makefile
This again addresses a `/usr/local/share/man/man1: No such file or directory` issue that was re-introduced by #17. (Sorry for the back and forth.)
> Makefile: add a default `PREFIX`; create `MANDIR` before installation

- README.md
It may be obvious for a curl project but I think the hint is still not wrong.
> README: add reference to required dependencies

- urler.c
adds the version of libcurl to the `--version` output. meant to look similar to `curl --version`. 
```
$ urler --version
urler version 0.1 libcurl/7.87.0 
```
should close #28
> added libcurl version to --version output

- urler.c
bunch of little memory leaks detected with `valgrind --leak-check=full`
> free all curl_slists and curl_easy_escape response

- test.pl
- trurl.1
- trurl.c
And allows := to store non-encoded strings.
Updated docs and added a test case
> trurl: now --set URL encodes by default

- README.md
- trurl.1
Updated JSON example to reflect the new JSON behavior (always an array, no trailing commas).
> Correct JSON example in README

- README.md
- test.pl
- trurl.1
- trurl.c
--trim can remove (parts of) components. Starting out with query support for removing specific "tuples".
Man page and README updates. Added test cases.
Fixes #50
> trurl: add --trim

- Makefile
This is useful to distribution packagers who may wish to set
```sh
INSTALL='install -p'
```
in order to preserve timestamps from the source tarball.
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_timestamps
> Add an INSTALL variable to the Makefile

- test-json.pl
- test.pl
- trurl.c
Earlier I posted a few changes on mastodon to get trurl to build on windows with vc2022: https://mastodon.social/@krishean/110141578599204303
If you build curl as a static library (using native tools command prompt):
```
set "basedir=%cd%"
cd "curl-8.0.1\winbuild"
nmake /f Makefile.vc MODE=static WITH_PREFIX=%basedir%\builds\curl-win64 ENABLE_SCHANNEL=yes GEN_PDB=no DEBUG=no MACHINE=x64
cd "%basedir%"
```
And then build trurl with these changes like so:
```
git clone https://github.com/curl/trurl.git
cd trurl
cl /O2 /DNDEBUG /MD /DCURL_STATICLIB /I "%basedir%\builds\curl-win64\include" /W4 /DWIN32 trurl.c /link /LIBPATH:"%basedir%\builds\curl-win64\lib" /out:trurl.exe /subsystem:console /nologo /machine:x64 libcurl_a.lib ws2_32.lib wldap32.lib advapi32.lib crypt32.lib Normaliz.lib
perl …
```
> Build and run tests on windows

- test.pl
- trurl.c
Per #80, `--trim()` will hang when other query string parameters (whether in the URL or added via `--append`) don't contain a value, and hence, no `=`
The same bad assumption (that all query parameters have a value) also leads us to fail to trim when the the parameter-to-be-queried doesn't have a value.
This fix separates the query string by `&` first, and then forgives those without an `=`
> Valueless query vs trim (#80)

- test.pl
- trurl.1
- trurl.c
Sorts the query pairs in a case insensitive alphabetical order
Added a test. Added to the man page.
Ref: #88
> add --sort-query

- trurl.c
Including for IDN names including emojis in names.
Example: trurl --json 'https://😃.com/x?emoji=%f0%9f%98%83'
Reported-by: Adam Katz
Fixes #72
> trurl: fix the json output of UTF-8 sequences

- .github/workflows/makefile.yml
- trurl.c
This sanitizer now passes the test suite.
> Free memory in JSON output & enable the clang address sanitizer

- trurl.1
- trurl.c
... also trim off trailing whitespace from URLs provided from a file
Reported-by: @andylima
Fixes #137
> support reading URL from a file without a newline

- trurl.1
fix for:
mandoc -T lint -W warning trurl.1 
mandoc: trurl.1:5:13: WARNING: cannot parse date, using it verbatim: 3 Apr 2023
> fix mandoc warning

- trurl.c
Some features in trurl are limited by the build-time libcurl version while some are restricted by the run-time. Providing both versions gives the full picture.
> provide built-with libcurl version info for --version

- .github/workflows/makefile.yml
- Makefile
- test.py
this also makes multiple arguments passable to `test.py` 
Also added make test-memory to makefile and added it to the ci stuffs
fixes #148
> added --with-valgrind to test.py

- tests.json
- trurl.c
trurl: json: print comma only after printing the first valid component
This fixes  trurl --json  outputting invalid JSON when not enough components are provided with --set.
Examples:
$ trurl --json
* Before:
```json
[
{
,
"path": "/"
}
]
```
* Now:
```json
[
{
"path": "/"
}
]
```
$ trurl --json -s host=hi
* Before:
```json
[
{
,
"host": "hi",
"path": "/"
}
]
```
* Now:
```json
[
{
"host": "hi",
"path": "/"
}
]
```
---
trurl: make sure to terminate the JSON array when aborting with --verify
> Output valid JSON when aborting with --verify and when the constructed URL is not valid.

- tests.json
- trurl.c
Currently trurl can output invalid URLs because `curl_url_get(CURLUPART_URL)` doesn't necessarily generate a valid URL if `curl_url_set()` is used on the URL handle.
A user could filter invalid URLs using another trurl process like `trurl -f file.txt -s 'scheme=s://' | trurl -f -`, but this is not great, especially if the user is using `--json`.
This patch tries to fix that; I'm not sure this is the best approach to fix this, but it at least, works in preventing trurl from outputting invalid URLs. Maybe there are better approaches.
Just like before, it is still possible to modify the meaning of the URL by setting invalid parts, but now at least the output of `--json` will be correct, e.g.:
```bash
$ trurl https://localhost -s 'scheme=s://example.org/'
s://example.org/://localhost/
$ …
```
> Make sure modified URLs are valid before printing them

- URL-QUIRKS.md
The difference makes sense for tests using said "quirks".
> URL-QUIRKS: specify if they are build-time or run-time requirements

- tests.json
- trurl.c
`curl_easy_unescape(NULL, str, ilen, &olen)` interprets 0 ilen as equivalent to `strlen(str)`. The code was not taking this into account, and was expecting the function to return "" in that case which was causing various bugs.
I replaced calls to `curl_easy_unescape()` with calls to a new `strurldecode()` wrapper function that calls `curl_easy_unescape()` with "" instead of str if ilen is 0 to work around the implicit `strlen()` behaviour.
`jsonString()` had the same problem. To fix this issue, I removed its implicit `strlen()` behaviour, and just called `strlen()` where necessary.
I also added some tests.
---
Output of `./trurl -g '{query:}' 'localhost?=bar'` before this patch:
```
bar=bar
```
Output of `./trurl -g '{query:}' 'localhost?=bar&&foo=baz&bar'` before this patch:
``` …
```
> trurl: fix query splitting

- tests.json
- trurl.c
previously if you trimmed a query and requested a json output trurl would print a set of empty key/value pairs
> no printing trimmed querys in json output

- trurl.c
trurl was exiting with 1 when running `--help`, this doesn't seem common for most programs so this PR has it return 0.
> --help exits with 0

- Makefile
Since we need an actual compiled trurl to run the valgrind tests, make test-memory depend on $(TARGET).
This also adds a .PHONY to test-memory, since test, checksrc, clean and install all have those.
> Makefile: make test-memory depend on $TARGET

- trurl.c
in the function getarg(), usedarg (a bool) was being set with `1`. It seems like most other bools in trurl are being set with `true/false`. not a particularly big deal but continuity is good
> usedarg set with true instead of 1

- tests.json
- trurl.c
Before this patch, when trurl encountered a invalid URL, it skipped it without freeing the URL handle.
This was not discovered earlier because all the tests with invalid URLs were using `--verify` so trurl aborted immediately when encountering invalid URLs, and valgrind couldn't detect the memory leak.
> trurl: fix URL handle leak for invalid URLs

- trurl.1
Remove trailing spaces from some lines, and fix some typos.
Capitalise ASCII, and URL where it makes sense.
Clarify that URL arguments can be specified without --url, and mention -- support.
Mention explicitly (not just in the examples), that if no base URL is provided, trurl will create a URL using the specified components.
---
Merge after #197 and #198
> trurl.1: various improvements

- test.py
- tests.json
- trurl.c
If a redirection fails, report the failure to stderr, and go to the next URL, or abort if running with --verify. Instead of silently ignoring the failure and carrying on.
This patch also renames urlfromstring() to seturl(), and implements --redirect with it so that curl_url_set() is called with the same flags used to parse base URLs.
Which means the following command will now work:
$ trurl --accept-space --redirect 'x://foo/a b' curl.se
x://foo/a%20b
> --redirect: don't silently ignore failed redirections.

- Makefile
At least on FreeBSD ports framework, DESTDIR is only defined during install stages, what makes it impossible to set proper make environment variables.
> Use DESTDIR only during install target

- tests.json
- trurl.1
- trurl.c
This patch restructures the JSON output with the following format:
```
{
"url": // same value as `{url}`
"parts": {
..., // urldecoded URL parts except the URL
},
"params": [
...
],
// other stuff
}
```
I decided to remove raw_port for now, since now I think it is less useful than it used to be.
This patch also reworks default output and -g.
`{raw:}` has been removed in favour of `{default:}`.
`{default:}` and `{puny:}` are "get modifiers" like `{:component}`, and may be specified in any order front of a component to modify the curl_url_get() flags used by trurl to get that URL.
`{default:}` makes trurl use CURLU_DEFAULT_PORT, use the libcurl-supported scheme's default port if one is not specified, and `{puny:}` makes trurl use CURLU_PUNYCODE  e.g.
* `{default:port}` will get 80 for …
> trurl: restructure JSON, add --default-port, --keep-port, --punycode

- .github/workflows/makefile.yml
- requirements.txt
The "packaging" python dependency has been removed with 3129d40
> ci: don't unnecessarily install "packaging" on macOS

- tests.json
/dev/null won't work in non-cygwin windows builds.
Fixes #213
> tests: use empty file instead of /dev/null

- Makefile
A couple of changes to allow trurl to be built with legacy toolchains and consistency when packaging.
> Adjust handling CFLAGS in Makefile

- tests.json
- trurl.1
- trurl.c
I accidentally implemented {:component} backwards in https://github.com/curl/trurl/commit/5bc344a704dad9413b9ff2406c163fb471f8e7be
Oops :)
This also caused URL parts in the json output to be urlencoded instead of urldecoded, since code is shared.
---
One of the reason we split URL parts into a separate object was to allow users to apply transformations on a part of the URL using a jq command that maps the parts object to a trurl command that constructs the new modified URL, e.g. like so:
```sh
trurl --json --url "$url" |
jq -r '
.[].parts |
(.path | values) |= ascii_upcase |# uppercase the path if it present
@sh "trurl \([ to_entries[] | "-s", "\(.key)=\(.value)"])"
' |
sh
```
But unfortunately, since the parts are urldecoded, this can't work.
libcurl, intead of returning a URL encoded …
> --json/--get: .[].parts and {component} should be urldecoded not encoded; add --urlencode

- .github/workflows/codeql.yml
- .github/workflows/codespell.yml
- .github/workflows/makefile.yml
- CONTRIBUTING.md
- checksrc.pl
- test.py
- tests.json
- trurl.c
- Remove trailing whitespace
- Remove whitespace from arrays
- Split up a long line
- Fix indentation
- Uppercase the manual page document title
- Fix typos
- Remove an unused import
- Remove unused struct member
- Reduce scope of some variables
- Remove unnecessary pointer check
- Avoid using the name of a function for a variable within that function
- Modernise Perl file open calls
- Only check trurl.c for spelling errors once
> Clean up whitespace, spelling/grammar, unused things, scope, shadowing, checks, file opens

- .github/workflows/reuse.yml
- .reuse/dep5
- LICENSES/curl.txt
- Makefile
- test.py
- trurl.1
- version.h
This job scans the git repository and verifies that all files have identifiable license and copyright information. Either in the file header or specified separately in .reuse/dep5
> GHA: add a REUSE job

- .gitignore
- winbuild/.vcpkg
- winbuild/README.md
- winbuild/trurl.sln
- winbuild/trurl.vcxproj
- winbuild/vcpkg-configuration.json
- winbuild/vcpkg.json
This adds build files for vc2022, and the needed include files and static libraries built from curl 8.0.1.
A CI job should be able to be added from: https://github.com/actions/starter-workflows/blob/main/ci/msbuild.yml with very minor chages, the `run: msbuild` line included in the example yml probably doesn't need any changes.
Other example msbuild commands:
```
msbuild /m /t:Clean,Build /p:Configuration=Debug /p:Platform=x86 trurl.sln
msbuild /m /t:Clean,Build /p:Configuration=Release /p:Platform=x86 trurl.sln
msbuild /m /t:Clean,Build /p:Configuration=Debug /p:Platform=x64 trurl.sln
msbuild /m /t:Clean,Build /p:Configuration=Release /p:Platform=x64 trurl.sln
```
I'll have to add in arm64 support in a future request, but I don't have the platform tools for that setup just yet.
> Add msvc build files

- tests.json
- trurl.1
- trurl.c
Added test case. Added docs.
Reported-by: Anselm Schüler
Fixes #227
> trurl: accept \* as a trim name to trim a literal asterisk name

- test.py
This is from Ref: https://github.com/curl/trurl/pull/189
separate stdout and stderr from each other, 
so we can get the error only if we want to find out where exactly the error occurred like this: ` make test 1> /dev/null `
and also add a `verbose` flag to print verbose if we want to see all the detail: ` python3 test.py --verbose `
> use stderr in test.py

- trurl.c
This PR adds a heap of fixes to undetected memory errors in trurl. These memory errors were discovered by building trurl against a debug version of libcurl and running `make test-memory` which discovered 55 memory errors on my machine. This PR doesn't fix all of them, but it does fix most of them. 
When running on my machine there are 2 tests which fail, both of which are a `--verify` test with early exits where the error message includes some string that was dynamically allocated. These two are tricky to fix with out reworking all of the error handling system. A simple fix is propagating the `struct option` to every function that could error and have the error function clean up the option struct after printing, this seems like a gross solution though and I thought that it should probably …
> fixed many undetected memory leaks in trurl

- tests.json
- trurl.c
I would prefer that `trurl` rejected URLs with schemes not supported by libcurl when I use it in combination with `curl`.
> trurl: add `--curl` to only count as valid URLs supported by libcurl

- Makefile
Some `LDFLAGS` are positional and affect how `LDLIBS` are interpreted.
Not a hard rule, but perhaps it's more usual to pass the libs last.
Ref: https://github.com/curl/curl-for-win/commit/764fa9b1db9dd531191563f36c82d75e1e53d823
> Makefile: pass `LDFLAGS` first, then `LDLIBS`

- trurl.c
This makes it possible to compile trurl with old C89 compilers without having to pass `-std=gnu99` or similar.
> avoid using variadic macro

- Makefile
- trurl.c
First I enabled all picky warnings from curl, then fixed all of them and
kept warning options enabled that needed fixing.
---
> enable more C compiler warnings and fix them

- trurl.c
Ref: https://github.com/curl/trurl/pull/250#issuecomment-1808626757
Suggested-by: Jacob Mealey
Closes #253
> move `{errorf,warnf}_low` common logic to a func

- .github/workflows/curl-for-win.yml
- test.py
- tests.json
- trurl.c
Add automated Windows builds and tests.
Use curl-for-win with llvm + mingw64, and a minimal libcurl build with
no external dependencies to build x64, ARM64 and x86 `trurl.exe`.
Boost build performance by not building the curl tool [EXPERIMENTAL].
Use a customized curl-for-win build with disabled TLS to further reduce
footprint and build time.
Non-UNITY libcurl builds can make turl binaries about 120KB smaller, but
they require 2x build times (4m vs. 2m), so opted not to use those here.
Also enable tests and fix issues along the way:                  
- libcurl with IDN support cannot be used because trurl itself lacks
UNICODE support and thus fails to accept non-ASCII strings via the
command-line.                                                  
```
expected: …
```
> ci: add Windows builds + tests

- trurl.c
Follow-up to bc67bb6056765b496580f661439fd3a9e6b26585
> fix copy-paste error in punycode macro

- trurl.c
Make it use the feature bitmask instead of walking through the list of
feature strings.
This isn't future-proof of course and the feature bitmask is almost full
as of curl v8.4.0. In case we need to check for a yet-to-be-added curl
feature that is only available through the feature string list, we will
have to reintroduce the list parsing.
Also avoid mid block variable declaration.
Ref: https://github.com/curl/trurl/pull/257#discussion_r1396470388
> simplify libcurl IDN detection

- tests.json
- trurl.c
Some tests require this feature present in libcurl to pass.
> add `imap-options` feature detection

- trurl.c
Follow-up to 67d81bf931bd66edb9b65396d399a840482e2182
> actually use the IMAP detection result to enable `imap-options`

- .github/workflows/curl-for-win.yml
- tests.json
For even smaller trurl binaries, and faster builds with libcurl built
without http support.
Also move http/80 tests to imap/143 for default-port tests.
We need IMAP already for IMAP options support.
Also mark tests relying on IMAP default port to require libcurl with
IMAP enabled.
ARM64 `trurl.exe` sizes:
- Before: 465KB https://github.com/curl/trurl/actions/runs/6903445608
- After, no http: 324KB https://github.com/curl/trurl/actions/runs/6903509264
- no http, no unity: 245KB https://github.com/curl/trurl/actions/runs/6903576741
- no http, no imap, unity: 243KB https://github.com/curl/trurl/actions/runs/6906597033
- no http, no imap, no unity: 189KB https://github.com/curl/trurl/actions/runs/6903738976
Closes #255
---
Pending: https://github.com/curl/curl/pull/12343 [MERGED]
> ci: build libcurl without http

- test.py
- tests.json
Adds the ability to skip tests that require UTF-8 encoding if the environment does not support UTF-8. It also cleaned up the feature checking logic.
Note: There is probably a much better way to do this, so feel free to leave suggestions.
fixes: #272
> Added UTF-8 detection to test runner

- tests.json
- trurl.c
Updated the tests accordingly.
Fixes #281
> if query is not updated, leave it untouched

- trurl.c
To help user detect typos and error out hard rather than to just not do what the user expected.
Ref: #236
> error when using an unrecognized URL component

- trurl.c
If the allocation of str fails, free the previous memory allocation in the error path.
> Free allocated pointer on OOM error

- tests.json
- trurl.c
With this change, we can write "trurl curl.se -g{host}", without having a space after "-g". This goes for all short options.
-v and -h are still treated specially because they cannot be combined with other options
Proposed-by: @mrnoname1000
Fixes #274
> short options need no space separation for the argument anymore

- tests.json
- trurl.c
Since it works with the same URL object, doing repeated appends will keep appending every loop which is not intended.
Add test cases to verify.
Reported-by: Jacob Mealey
Fixes #299
> trurl: only append the first iterate loop

- trurl.c
The warn function adds the newline(s) itself
> remove a suprious trailing newline from a warning

- trurl.c
Reported-by: Krishean Draconis
Bug: https://tech.lgbt/@krishean/112871913828723815
> trurl: use casecompare instead of a strncasecmp define

- trurl.c
`query_is_modified` is global and does not get reset at every call of `singleurl()` so, if a query is modified for a URL, the query for all the following URLs is automatically considered modified.
Additionally `--trim` and `--replace` were setting `query_is_modified` to true unconditionally as long as a `--trim` or `--replace` option is passed to trurl, even if no changes were made.
Which made it effectively just a convoluted way to check if any of `--trim`, `--replace`, `--append query`, `--sort-query` was passed.
Since `singleurl()` was made recursive to implement `--iterate`, I could not just add `query_is_modified = false` at the start of `singleurl()` to fix the problem, so I have refactored the code to not need a global.
> singleurl: fix query_is_modified

- trurl.c
Rather than continuing and acting weirdly.
> trurl: on strdup() failures, exit immediately

- tests.json
- trurl.1
- trurl.c
Makes it work like --append query= already does.
- update man page
- update test cases
Fixes #321
> trurl: make --replace URL encode the provided data argument

- tests.json
- trurl.c
To properly handle https://example.com/?%611&a2&a3 --trim query=a*, trurl now "normalizes" the query pairs by an extra round of URL decode + encode.
If a query pair gets normalized, consider it modified which in turn triggers a URL update. Thus
trurl 'https://example.com/?%611&a2&a3'
outputs
https://example.com/?a1&a2&a3
The query part URL encodes spaces to pluses (and vice versa). Note that %20 in the query in the input URL will be normalized to a +.
Updated several tests accordingly.
Reported-by: Emanuele Torre
Fixes #326
> trurl: "normalize" query pairs

- tests.json
- trurl.c
Extract the path once, do all the appends then set the final version once in the end. Instead of doing it every loop.
> trurl: optimize the path append loop

- tests.json
- trurl.c
trurl now URL-decodes + URL-encodes the path so that %-sequences that can be expressed as ASCII are shown as ASCII and %-sequences are unified to lowercase hex etc.
Added test case to verify
Fixes #329
> trurl: canonicalize the path

- tests.json
- trurl.1
- trurl.c
To make the name better match its functionality. Keep support for the old name (but don't advertise it).
Alphasort the -h output
Add test to verify that both names work.
> trurl: rename --force-replace to --replace-append

- trurl.c
> trurl: fix memory leaks on errors

- tests.json
- trurl.c
- trurl.md
using a `must:` prefix for gets makes trurl return error for missing parts
If libcurl is new enough a present but zero-length query or fragment does not cause an error when `must:` is used.
> support a must: prefix for gets

- tests.json
- trurl.c
Like for this:
trurl example.com/%18 -g '{path}'
It was previously prevented.
Added test. Also indented the entire JSON file so check the diff without whitespace if you want to see only this added test.
Fixes #338
> trurl: accept "control codes" in get output

- RELEASE-NOTES
- mkrelease
The tarball contains a trurl.1, the nroff/manpage version of trurl.md, generated with cd2nroff from curl/scripts
> mkrelease: generate a release tarball

- mkrelease
- trurl.md
- put the version number on the right place
- escape the backslash in markdown correctly
Fixes #347
> manpage: fix 0.15 mistakes

- Makefile
Simply skips the operation if there is no .1 file around. The manpage version is shipped in tarballs but is not present in git.
> Makefile: check for trurl.1 before installing

- tests.json
- trurl.c
Passing a query pair with a blank left side like '=a' was similarly mistreated.
Follow-up to 06b59453076e23e66e38e
Added test case to verify.
> trurl: fix handling of query pair with blank left side

- tests.json
- trurl.c
Match how libcurl does it. Add two tests to verify.
Fixes #357
Reported-by: Peter Schilling
> trurl: make sure URL encoded %-hex is done lowercase

- tests.json
- trurl.c
Previously trurl would output a "note" when it did not replace a query name and instead appends it, but since that is just part of its documented behavior that output seems superfluous and rather annoying.
Update two tests accordingly.
> trurl: silence --replace-append when appending

- README.md
- tests.json
- trurl.c
- trurl.md
--trim is now deprecated. When we added that we thought we would trim other components over time but that has not materialized. Switching to --qtrim makes for easier command lines with no functionality loss.
--trim is no longer displayed in the help output but is still tested in several test cases.
> trurl: introduce --qtrim for trimming queries (only)

- trurl.c
... to make it clearer that it is for outputs.
> trurl.c: clarify the --help text for --urlencode

- tests.json
- --punycode
- use same options twice
- use options without arguments
> tests.json: add more tests

- .gitignore
- Makefile
- completions/_trurl.zsh.in
- completions/generate_completions.sh
This PR introduces a script `generate_completions.sh` which extracts the command line options from `trurl.md` and sorts them in to different buckets: standalone (things like `--json`, `--accept-space`), component options (things like `--set`, `--iterate` which take a `component=` directly after), _random options_ (things like `--qtrim`, `--url-file` that take an option but we don't control what it is), and the components. The _trurl.zsh.in is a template that these different list of options are inserted into. 
I also added a `completions` task to the Makefile, and updated the install to copy them to `/usr/local/share/zsh/site-functions` if the completion has been built.
> Generate ZSH completions base on trurl.md

- Makefile
When not installing the manpage there is no use in creating the directory
Fixes f3523912562 Makefile: check for trurl.1 before installing
> Makefile: only create MANDIR when manpage is installed

- trurl.md
Discovered by Debian's linting tool
> trurl.md: fix typo

- Makefile
PR #379 has crosswired paths and the latest release does not build an install completions as expected.
> Fixup completions build & install

- trurl.c
One instance of a pointer coming from curl_maprintf() was freed with a
normal free() which breaks and causes ASAN/valgrind to complain when
using a debug-enabled libcurl. Since the function could return a normal
heap-allocated pointer or a curl-allocated one, copy the string and
curl_free() the original.
Closes #393
> trurl: use curl_free() on a pointer coming from curl_maprintf()
