.gitignore
I've copied from https://github.com/github/gitignore/blob/main/C.gitignore
and added `/urler` at the top to also ignore the compiled file
=> Add gitignore based on GitHub template

README.md
I've added some very basic instructions in the README to help compile the source.
=> Add install instruction on Linux

README.md
```console
$ urler --set-host example.com --set-scheme ftp
ftp://example.com/
```
=> README: correct --set-scheme example output

urler.1, urler.c
=> urler: --url-file reads URLs from a file or stdin

trurl.c
=> trurl: deal with a URL file in a streaming manner

trurl.1
just a minor wording correction :)
=> fix wording in manpage

test.pl, trurl.c
=> trurl: fix --append query when no previous query exists

Makefile, test-json.pl, trurl.c
To properly work with many URLs
Fixes #49
=> trurl: output JSON as an array

trurl.1, trurl.c
Sorted the options in the man page
=> add --verify to make trurl check the URL strictly

test.pl
This shouldn't require any dependency management, since Test::More has
been provided with Perl since Perl release 5.6.2
perl -MModule::CoreList -E 'print Module::CoreList->first_release('Test::More');'
5.006002
=> Use Test::More inside of test.pl

test.pl, trurl.c
=> trurl: setting port to a blank should clear it

trurl.c
=> flush stdout after handling every URL

test.pl, trurl.1, trurl.c
Added tests. Added text in man page.
Fixes #99
=> support showing {query:key}

trurl.c
This still fails some tests due to missing functionality in the older versions.
=> add support for building with older libcurl versions

.github/workflows/makefile.yml
The code doesn't currently pass the address or memory sanitizers, but
that should be a goal.
=> CI: Add a UBSAN build

test.py, tests.json
I have now taken all the tests, both json and not and put them in tests.json
Then i have disabled stderr testing for now, they are still present in json files for future.
I added the following features:
- run just a specific test case
- verify the exit code (to better test errors)
In order to run specific cases simply run test.py index,index,index (comma sep no spaces)
I planted a few issues for testing purposes.
closes #74
=> added test script for python

test.py, tests.json
=> Tests: Activated stderr and fixed program exit code

test.pl, tests.json, trurl.1, trurl.c
Add test. Add docs.
Fixes #127
=> handle %00 sequences in {query:key} output

.github/workflows/makefile.yml
Resolves #153.
Note that CI is expected to fail because of #152.
=> Add macOS CI

Makefile, test.py
To avoid running tests without compiling first :D
=> Makefile: make  test  target depend on trurl

URL-QUIRKS.md, tests.json, trurl.1, trurl.c
Added two tests. Added docs.
Fixes #64
=> offer {puny:host} and {puny:url} for --get

tests.json, trurl.1
Also added a test for --json that outputs all components
=> document the JSON output format in the man page

.github/workflows/makefile.yml
=> makefile.yml: rename the jobs

trurl.c
declaration of 'i' shadow a previous local (in lines 702 & 735)
at this moment can't cause any problems but in the future, they may!
=> declaration of 'i' shadow a previous local

Makefile, trurl.c
=> makefile: use -Wshadow and -Werror by default

tests.json, trurl.c
Add test to verify
Fixes #190
Reported-by: @emanuele6
=> trurl: refuse setting same component in --set as --iterate

checksrc.pl, trurl.c
Imported checksrc.pl as of upstream commit 9ce7eee070 from curl.
Reported-y: @emanuele6
Fixes #192
=> trurl.c: fix minor code style nits

tests.json, trurl.1, trurl.c
=> trurl: add a new --no-guess-scheme option to disable scheme guessing

test.py, tests.json, trurl.c
Fixes #184 
I used the predefines to determine the names of the features, but I feel like it doesn't provide very much insight into what features are added so if folks have a better naming idea then that would be swell. I also only modified the punycode tests because those were the only ones failing, but it may be useful/cleaner to have all of them use the feature names instead of the version number.
=> Use feature list for tests

test.py
It looks like one comment line was missed during the feature list update.
=> Update comment on line 130 in test.py

test.py
Add a function to check if "valgrind" is installed.
@bagder
=> check valgrind function

trurl.c
Ref: https://github.com/curl/trurl/pull/284#discussion_r1570645001
=> expand the warning on "internal problem"

RELEASE-NOTES, RELEASE-PROCEDURE.md, mkrelease
- updates trurl.1 and version.h accordingly
- update RELEASE-PROCEDURE.md to mention this
Reported-by: gnomon- on github
Fixes #315
=> mkrelease: script to run at release

tests.json
https://ex%61mple.com/h%61s/?wh%61t => https://example.com/has/?what
=> tests: add a simple URL canonicalization test

trurl.md
... the same order as in the trurl -h output
=> trurl.md: list the options alphabetically

tests.json, trurl.c
Add several tests to verify.
Reported-by: Peter Schilling
Fixes #351
=> trurl: fix misbehavior on empty query param

tests.json, trurl.c
=> trurl: normalize the fragment

Makefile, mkrelease, scripts/cd2nroff
From curl's commit b0009d0216a09a3e0ffa34fdb
Build the man page in the makefile
=> scripts: import cd2nroff from curl

tests.json, trurl.c
Added several new test cases for it
Fixes #387
Reported-by: joveian on github
=> trurl: handle zero length query pairs
